travis:
  secure:
    BINSTAR_TOKEN: n+LCRgb4J7yHaSSb9QKTPnJ4Hqpnq6zzDKKtun4CuaFchrI9RJaOxEHkBcnjis4rB1DSMSorbxhVFZvSa8sYESnZjD//FOvu6ZukOA9bH2JKPav8RSG9SqyV9NeNQoXu/Nc5L914G3h7MSTlP3PE95tr10g8oyPnluTb6gdy3R82Rs8sqUZa5XxkTsfXMKEFKx66MpGCCdU4Vg0TMj3uwOEA7MeDdjNXCLgP/1tybARCo+5LO4Z7GzCZIjIRwLmr2aerLlVsuw3hvJtvYuWnqTxFvg3l1q+y7TybFT34O7VBvPlJu9DaG8qJYufVbkX8XbFOrVzjyAREBzfM17Ab1fL5awI9Tm4WfoOjvvshbuzszGdqNz0JEGkSBPMttfzHlaOMhyAHAC9wz1ge0CKl9kmm4pYb6F/g+1113MiVnp8MoorHpTiBg066wUbQcn5+AhQiO8/fJ4U0saAmzMBwjG44+gPo7Raj5qlpmbApw2GqTcs0N3immAcJlSVv2iTvHDl+CuIHBzwVd2dBHRIc16K8BK7xLSjuT+tW1SfLiRxCRJ6QlS5TDeKnOaQpevumZGwhGZqQ9N4LNBabwHnAXt32XA/aSMxb9bsO1t9pomHqr6VjZQSyo91v0cRcOn26rXML2SZLLiLLLgkVzcunP+aADMUYI2zjSFsVvlTFe2A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
